_common/lib: !include "../package-lib.yaml"

name: stellar-sdk-core
version: 0.1.0.0
<<: *meta
<<: *defaults

library:
  source-dirs: src
  dependencies:
  - aeson
  - array
  - base64-bytestring
  - base64-bytestring-type
  - bytestring
  - binary
  - cryptonite
  - lens
  - memory
  - newtype
  - refined
  - semigroups
  - static-text
  - text
  exposed-modules:
  - Stellar
  - Stellar.Core.Lens
  - Stellar.Crypto
  - Stellar.Core.Types
  - Stellar.Core.Types.Internal
  - Stellar.Core.Types.Key
  - Data.Binary.Extended
